### ISSUE TITLE
无法正确进入验证

### ISSUE THREAD

**Issue by zenjava** [eggjs/egg-passport-local#1]
passport按你的代码测试，无法进入 app.passport.verify方法。
是不是需要其他什么配置。

**Comment by leiyanggz** [comment]
没有其他设置，有其他报错信息吗，你是post到 /login 这个端口吗？请检查下routing是否正确。 如果你安装了egg-passport的话，没有引入egg-passport-local也是会调用 app.passport.verify，这个是egg-passport统一的调用函数，引入egg-passport-local如果有问题的话会报错 cannot find local strategy, blablabla

**Comment by sinchang** [comment]
我也遇到类似的问题，始终无法进入app.passport.verify方法，也没什么报错信息，麻烦帮忙看下。

repo: https://github.com/sinchang/authentication-with-egg

**Comment by leiyanggz** [comment]
把login中的name="email"换成name="username"就可以了

**Comment by leiyanggz** [comment]
如果业务需要name="xxx"，自己修改下插件中的app.js把username换成你需要的参数

**Comment by sinchang** [comment]
可以了，谢谢。可定制性不是很强，如果能 config 就更好了。

**Comment by leiyanggz** [comment]
恩，是的，谢谢建议！

**Comment by atian25** [comment]
其实是支持的，配置下 `config.passportLocal.usernameField` 即可
