### ISSUE TITLE
求解，下载找不到包，npm ERR! 404 Not Found: egg-passsport-local@latest

### ISSUE THREAD

**Issue by cmygit** [eggjs/egg-passport-local#6]
你好，我照着readme.md的例子的时候，安装这个包失败了。
命令：npm i egg-passsport-local --save
输出信息：
npm ERR! code E404
npm ERR! 404 Not Found: egg-passsport-local@latest
我去npm官网搜了一下，也没有搜到这个包。

**Comment by atian25** [comment]
`npm i egg-passport-local --save` 多了一个 `s`，已更新文档。

PS，后续 issue 入口在 egg 那边。
